#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, dgtl1,  right_drive_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  left_drive_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  right_6Bar_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  left_6Bar_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  conveyor_encoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           left_back_drive, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           left_6Bar_B,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right_front_drive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           conveyor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           left_front_drive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           strafer,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           left_6Bar_A,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           right_6Bar_A,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right_6Bar_B,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right_back_drive, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c" //Main competition background code...do not modify!
#include "VEX_D_Combos.h"

void pre_auton()
{
	resetEncoders();
}

task autonomous()
{
	basicStack();
	//triStack();
}

task usercontrol()
{
	while(true)
	{
		updateChannels();
		updateCombos();
		updateDrive();
		updateManip();
		updateEncoders(left_6Bar_encoder, right_6Bar_encoder);
	}

}
